### ISSUE TITLE
Database has a view to display people

### ISSUE THREAD

**Issue by KhaledAlfayez237** [Connected-Networks/Connected-Networks-Project#20]
**Requirements**
- [x] The database has a view for the data that contains all the needed data to be displayed on the frontend:
  - [x] Name
  - [x] Current company
  - [x] Current position
  - [x] Comment
  - [x] LinkedInURL

**Acceptance Criteria**
- [x] A script exists that can create the view.
- [x] The database can query the view.

**Comment by DRSisco** [comment]
The purpose of an ORM is so you dont have to make scripts/views.  https://sequelize.org/master/manual/querying.html
To be honest... views scare me and I would advise avoiding them until a need arises where it is the most optimal situation.
https://sequelize.org

You really shouldn't have any Database issues. Just migrations, so the tables/columns exist.

**Comment by MongoSP** [comment]
Completed Multiple:
-Name
-Current company
-Current position
-Comment
-LinkedInURL
There is a caveat though (and Thus why I haven't marked this down as done): This uses a SQL generated stored procedure that needs to ALTER the employee history table. This is because of issues arising from GROUP BY and ORDER BY ignoring the work of the other. 

I also still have yet to look into sequelize, but I am not sure if it would have been able to solve this problem without sending the entire table to the backend.

(Current time for this stored procedure has taken 3 hours and 15 minutes.

**Comment by MongoSP** [comment]
Merged into milestone 2, closing issue.
